In [3]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.3.1 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [4]:
import numpy as np
np.__version__

'2.0.2'

In [22]:
a = np.arange(15).reshape(5, 3)   #arrange natural nos until 15
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [21]:
print(a.shape," ",a.ndim," ",a.size)

(5, 3)   2   15


In [23]:
b = np.array([(1.5, 2, 3), (4, 5, 6)])

In [28]:
np.array([[1, 20.2], [3, 4]], dtype=int)

array([[ 1, 20],
       [ 3,  4]])

In [30]:
np.array(([1, 20.2], [3, 4]), dtype=complex)

array([[ 1. +0.j, 20.2+0.j],
       [ 3. +0.j,  4. +0.j]])

In [34]:
np.ones([2,3,3],dtype=np.int16)

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]], dtype=int16)

In [39]:
np.arange(1,5,0.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [42]:
from numpy import pi
np.linspace(0, 2, 9)  #prevent floating precision 9 is the no of terms

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [43]:
np.arange(10000)

array([   0,    1,    2, ..., 9997, 9998, 9999])

In [44]:
b=np.arange(10)
b**2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [46]:
A = np.array([[1, 1],
              [0, 1]])
B = np.array([[2, 0],
              [3, 4]])
A * B     # elementwise product


array([[2, 0],
       [0, 4]])

In [47]:
A @ B     # matrix product
A.dot(B)  # another matrix product

array([[5, 4],
       [3, 4]])

In [48]:
rg = np.random.default_rng(1)  # create instance of default random number generator
a = np.ones((2, 3), dtype=int)
b = rg.random((2, 3))
a *= 3
a


array([[3, 3, 3],
       [3, 3, 3]])

In [49]:
b += a
b


array([[3.51182162, 3.9504637 , 3.14415961],
       [3.94864945, 3.31183145, 3.42332645]])

In [52]:
a += b  # b is not automatically converted to integer type

UFuncTypeError: Cannot cast ufunc 'add' output from dtype('float64') to dtype('int64') with casting rule 'same_kind'

In [54]:
a = np.ones(3, dtype=np.int32)
b = np.linspace(0, pi, 3)
b.dtype.name
c = a + b
c
c.dtype.name
d = np.exp(c * 2j)
d


array([-0.41614684+0.90929743j,  0.41614684-0.90929743j,
       -0.41614684+0.90929743j])

In [19]:
rg = np.random.default_rng(100) #seed remove 100
a = rg.random((2, 3))
a

array([[0.83498163, 0.59655403, 0.28886324],
       [0.04295157, 0.9736544 , 0.5964717 ]])

In [23]:
a = np.arange(10)**3
a
a[2]
a[2:5]
# equivalent to a[0:6:2] = 1000;
# from start to position 6, exclusive, set every 2nd element to 1000
a[:6:2] = 1000
a
                                                                                
                                                                            

array([1000,    1, 1000,   27, 1000,  125,  216,  343,  512,  729])

In [27]:
a[::-1] # reversed a

array([ 729,  512,  343,  216,  125, 1000,   27, 1000,    1, 1000])

In [28]:
 a[::-2]  

array([729, 343, 125,  27,   1])

In [30]:
def f(x, y):
    return 10 * x + y
b = np.fromfunction(f, (5, 4), dtype=int)
b


array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [35]:
b[1:80, 0:2]  #no error for out of index!!

array([[10, 11],
       [20, 21],
       [30, 31],
       [40, 41]])

In [45]:
c = np.array([[[  0,  1,  2],  # a 3D array (two stacked 2D arrays)
               [ 10, 12, 13]],
              [[100, 101, 102],
               [110, 112, 113]]])
c.shape
c[1,1, ...]  # same as c[1, :, :] or c[1]


array([110, 112, 113])

In [46]:
for element in c.flat:
    print(element)

0
1
2
10
12
13
100
101
102
110
112
113


In [48]:
a.ravel()  # returns the array, flattened
a.reshape(5, 2)  # returns the array with a modified shape
a.T  # returns the array, transposed
a.T.shape
a.shape

#impp they dont mess with original array

(10,)

In [49]:
#a.resize(5,2)  changes the original one

In [53]:
#The function column_stack stacks 1D arrays as columns into a 2D array. It is equivalent to hstack only for 2D arrays:
from numpy import newaxis
a = np.array([4., 2.,3])
b = np.array([3., 8.,6])
np.column_stack((a, b))  # returns a 2D array


array([[4., 3.],
       [2., 8.],
       [3., 6.]])

In [55]:
#like pointers pointing to same memory location
a = np.array([[ 0,  1,  2,  3],
              [ 4,  5,  6,  7],
              [ 8,  9, 10, 11]])
b = a            # no new object is created
b is not a           # a and b are two names for the same ndarray object

False

In [57]:
#understood shallow copy create a diff outer list but has same reference to inner one changing one changes other
#and deep copy creates a seperate copy

In [58]:
a = np.arange(30)
b = a.reshape((2, -1, 3))  # -1 means "whatever is needed"
b.shape
b


array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]],

       [[15, 16, 17],
        [18, 19, 20],
        [21, 22, 23],
        [24, 25, 26],
        [27, 28, 29]]])