In [111]:
#implementing Multiple linear regression
import pandas as pd
import numpy as np

In [112]:
df = pd.read_csv("Housing.csv")
df

price  area  bedrooms  bathrooms  stories mainroad guestroom basement  \
0    13300000  7420         4          2        3      yes        no       no   
1    12250000  8960         4          4        4      yes        no       no   
2    12250000  9960         3          2        2      yes        no      yes   
3    12215000  7500         4          2        2      yes        no      yes   
4    11410000  7420         4          1        2      yes       yes      yes   
..        ...   ...       ...        ...      ...      ...       ...      ...   
540   1820000  3000         2          1        1      yes        no      yes   
541   1767150  2400         3          1        1       no        no       no   
542   1750000  3620         2          1        1      yes        no       no   
543   1750000  2910         3          1        1       no        no       no   
544   1750000  3850         3          1        2      yes        no       no   

    hotwaterheating airconditioning  parking prefarea furnishingstatus  
0                no             yes        2      yes        furnished  
1                no             yes        3       no        furnished  
2                no              no        2      yes   semi-furnished  
3                no             yes        3      yes        furnished  
4                no             yes        2       no        furnished  
..              ...             ...      ...      ...              ...  
540              no              no        2       no      unfurnished  
541              no              no        0       no   semi-furnished  
542              no              no        0       no      unfurnished  
543              no              no        0       no        furnished  
544              no              no        0       no      unfurnished  

[545 rows x 13 columns]

In [113]:
y=df.iloc[:,0:1]
X=df.iloc[:,1:]

In [114]:
y

price
0    13300000
1    12250000
2    12250000
3    12215000
4    11410000
..        ...
540   1820000
541   1767150
542   1750000
543   1750000
544   1750000

[545 rows x 1 columns]

In [115]:
X

area  bedrooms  bathrooms  stories mainroad guestroom basement  \
0    7420         4          2        3      yes        no       no   
1    8960         4          4        4      yes        no       no   
2    9960         3          2        2      yes        no      yes   
3    7500         4          2        2      yes        no      yes   
4    7420         4          1        2      yes       yes      yes   
..    ...       ...        ...      ...      ...       ...      ...   
540  3000         2          1        1      yes        no      yes   
541  2400         3          1        1       no        no       no   
542  3620         2          1        1      yes        no       no   
543  2910         3          1        1       no        no       no   
544  3850         3          1        2      yes        no       no   

    hotwaterheating airconditioning  parking prefarea furnishingstatus  
0                no             yes        2      yes        furnished  
1                no             yes        3       no        furnished  
2                no              no        2      yes   semi-furnished  
3                no             yes        3      yes        furnished  
4                no             yes        2       no        furnished  
..              ...             ...      ...      ...              ...  
540              no              no        2       no      unfurnished  
541              no              no        0       no   semi-furnished  
542              no              no        0       no      unfurnished  
543              no              no        0       no        furnished  
544              no              no        0       no      unfurnished  

[545 rows x 12 columns]

In [116]:
X.shape

(545, 12)

In [117]:
def change (X):
 bool_columns = ['mainroad', 'guestroom', 'basement', 'hotwaterheating', 'airconditioning', 'prefarea']

 for column_name in bool_columns:
  X.loc[X[column_name] == 'yes', column_name] = 1
  X.loc[X[column_name] == 'no', column_name] = 0

 column_name='furnishingstatus'
 X.loc[X[column_name] == 'furnished', column_name] = 2
 X.loc[X[column_name] == 'semi-furnished', column_name] = 1
 X.loc[X[column_name] == 'unfurnished', column_name] = 0
 return X


In [118]:
X=change(X)
X

area  bedrooms  bathrooms  stories mainroad guestroom basement  \
0    7420         4          2        3        1         0        0   
1    8960         4          4        4        1         0        0   
2    9960         3          2        2        1         0        1   
3    7500         4          2        2        1         0        1   
4    7420         4          1        2        1         1        1   
..    ...       ...        ...      ...      ...       ...      ...   
540  3000         2          1        1        1         0        1   
541  2400         3          1        1        0         0        0   
542  3620         2          1        1        1         0        0   
543  2910         3          1        1        0         0        0   
544  3850         3          1        2        1         0        0   

    hotwaterheating airconditioning  parking prefarea furnishingstatus  
0                 0               1        2        1                2  
1                 0               1        3        0                2  
2                 0               0        2        1                1  
3                 0               1        3        1                2  
4                 0               1        2        0                2  
..              ...             ...      ...      ...              ...  
540               0               0        2        0                0  
541               0               0        0        0                1  
542               0               0        0        0                0  
543               0               0        0        0                2  
544               0               0        0        0                0  

[545 rows x 12 columns]

In [119]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42)

In [120]:
X_train.shape ,y_test.shape

((436, 12), (109, 1))

In [121]:
#Now we will use OLS method of regression
X_train_m = X_train.to_numpy()
X_test_m = X_test.to_numpy()

In [122]:
type(X_train_m) , X_train_m.shape

(numpy.ndarray, (436, 12))

In [123]:
shape=(X_train_m.shape[0],1)
shape1=(X_test_m.shape[0],1)

In [124]:
X_train_m , X_train_m.shape

(array([[6000, 3, 2, ..., 1, 0, 2],
        [7200, 3, 2, ..., 3, 0, 1],
        [3816, 2, 1, ..., 2, 0, 2],
        ...,
        [4500, 3, 2, ..., 1, 0, 2],
        [4040, 2, 1, ..., 0, 0, 0],
        [5500, 3, 2, ..., 1, 0, 1]], shape=(436, 12), dtype=object),
 (436, 12))

In [125]:
X_train_m = X_train.to_numpy().astype(int)
y_train_m = y_train.to_numpy().astype(int)

X_test_m = X_test.to_numpy().astype(int)

In [126]:
X_train_m = np.hstack((np.ones(shape), X_train_m))
X_test_m = np.hstack((np.ones(shape1), X_test_m))
X_train_m

array([[1.000e+00, 6.000e+03, 3.000e+00, ..., 1.000e+00, 0.000e+00,
        2.000e+00],
       [1.000e+00, 7.200e+03, 3.000e+00, ..., 3.000e+00, 0.000e+00,
        1.000e+00],
       [1.000e+00, 3.816e+03, 2.000e+00, ..., 2.000e+00, 0.000e+00,
        2.000e+00],
       ...,
       [1.000e+00, 4.500e+03, 3.000e+00, ..., 1.000e+00, 0.000e+00,
        2.000e+00],
       [1.000e+00, 4.040e+03, 2.000e+00, ..., 0.000e+00, 0.000e+00,
        0.000e+00],
       [1.000e+00, 5.500e+03, 3.000e+00, ..., 1.000e+00, 0.000e+00,
        1.000e+00]], shape=(436, 13))

In [127]:
X_train_m.shape


(436, 13)

In [128]:
beta = (np.linalg.inv(X_train_m.T @ X_train_m) @ X_train_m.T) @ y_train_m #minimised beta

In [129]:
beta.shape,beta

((13, 1),
 array([[-1.27711167e+05],
        [ 2.35848772e+02],
        [ 7.85744924e+04],
        [ 1.09711727e+06],
        [ 4.06223164e+05],
        [ 3.66824192e+05],
        [ 2.33146766e+05],
        [ 3.93159779e+05],
        [ 6.87881311e+05],
        [ 7.85550579e+05],
        [ 2.25756514e+05],
        [ 6.29901661e+05],
        [ 2.10397118e+05]]))

In [130]:
intercept=beta[0]
intercept

array([-127711.16739247])

In [131]:
coeff=beta[1:]
coeff

array([[2.35848772e+02],
       [7.85744924e+04],
       [1.09711727e+06],
       [4.06223164e+05],
       [3.66824192e+05],
       [2.33146766e+05],
       [3.93159779e+05],
       [6.87881311e+05],
       [7.85550579e+05],
       [2.25756514e+05],
       [6.29901661e+05],
       [2.10397118e+05]])

In [132]:
coeff.shape

(12, 1)

In [133]:
def check (X_check):
    y_check= X_check@coeff + intercept
    return y_check

In [134]:
type(X_test)
X_test

area  bedrooms  bathrooms  stories mainroad guestroom basement  \
316  5900         4          2        2        0         0        1   
77   6500         3          2        3        1         0        0   
360  4040         2          1        1        1         0        0   
90   5000         3          1        2        1         0        0   
493  3960         3          1        1        1         0        0   
..    ...       ...        ...      ...      ...       ...      ...   
15   6000         4          1        2        1         0        1   
357  6930         4          1        2        0         0        0   
39   6000         4          2        4        1         0        0   
54   6000         3          2        2        1         1        0   
155  6100         3          2        1        1         0        1   

    hotwaterheating airconditioning  parking prefarea furnishingstatus  
316               0               0        1        0                0  
77                0               1        0        1                2  
360               0               0        0        0                1  
90                0               1        0        0                1  
493               0               0        0        0                2  
..              ...             ...      ...      ...              ...  
15                0               0        2        0                1  
357               0               0        1        0                2  
39                0               1        1        0                1  
54                0               1        1        0                1  
155               0               0        2        1                2  

[109 rows x 12 columns]

In [135]:
X_test_m

array([[1.00e+00, 5.90e+03, 4.00e+00, ..., 1.00e+00, 0.00e+00, 0.00e+00],
       [1.00e+00, 6.50e+03, 3.00e+00, ..., 0.00e+00, 1.00e+00, 2.00e+00],
       [1.00e+00, 4.04e+03, 2.00e+00, ..., 0.00e+00, 0.00e+00, 1.00e+00],
       ...,
       [1.00e+00, 6.00e+03, 4.00e+00, ..., 1.00e+00, 0.00e+00, 1.00e+00],
       [1.00e+00, 6.00e+03, 3.00e+00, ..., 1.00e+00, 0.00e+00, 1.00e+00],
       [1.00e+00, 6.10e+03, 3.00e+00, ..., 2.00e+00, 1.00e+00, 2.00e+00]],
      shape=(109, 13))

In [136]:
selected=23
predicted=check(X_test_m[selected,1:])
predicted

array([4762590.14920606])

In [137]:
X_test.iloc[selected:selected+1]

area  bedrooms  bathrooms  stories mainroad guestroom basement  \
174  3800         3          1        2        1         1        1   

    hotwaterheating airconditioning  parking prefarea furnishingstatus  
174               0               0        1        1                0

In [138]:
y_test.iloc[selected:selected+1]

price
174  5250000